import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/** Flat config. `next lint` is deprecated in Next 15.5, so the DoD's lint
 *  gate runs the ESLint CLI directly and non-interactively.
 *  next-env.d.ts is generated by Next and is not ours to lint. */
const config = [
  { ignores: ['.next/**', 'node_modules/**', 'out/**', 'public/**', 'next-env.d.ts'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;
