#!/usr/bin/env node
/**
 * THE SPRINT 13 GATE — a full crawl audit.
 *
 * `docs/SEO_LLM_STRATEGY.md` §8 defines "clean" as ten things. This script
 * checks all ten and fails on any of them, so the gate is a command rather
 * than a reading of the site.
 *
 *   1. Full crawl with JavaScript disabled
 *   2. Every schema type validated
 *   3. No duplicate titles or descriptions
 *   4. Exactly one H1 per page
 *   5. Every page has an inbound internal link
 *   6. Sitemap matches published content exactly
 *   7. llms.txt current
 *   8. Every 301 resolves in one hop, no chains
 *   9. No [[NEEDS_VERIFICATION]] token on any public page
 *  10. No page indexed that should be noindex
 *
 * Plus, since the restart, a real share image on every indexable page
 * (CLAUDE.md §7; V45 went unnoticed for two sprints without it).
 *
 * ── "With JavaScript disabled" is the whole point, and it is free here ──────
 *
 * `fetch` runs no JavaScript. So every assertion below is made against the
 * HTML a crawler actually receives, which is the failure this rebuild exists
 * to fix: the old site put its specifications behind a client-only tab and an
 * assistant asking "what does the anti-jammer tracker support" saw a page with
 * no specifications on it.
 *
 * ── No new dependency ──────────────────────────────────────────────────────
 *
 * No cheerio, no jsdom. The extractions below are regex over HTML, which is
 * the wrong tool for parsing HTML in general and the right one here: the
 * markup is generated by our own templates, the fields are shallow, and a
 * dependency added to a launch audit is a dependency in the launch audit's
 * supply chain. Where a regex would be genuinely unsafe — JSON-LD — the text
 * is handed to JSON.parse and the parser does the work.
 *
 * Usage:
 *   node scripts/crawl-audit.mjs [baseUrl]        # default http://localhost:3000
 *   node scripts/crawl-audit.mjs --json           # machine-readable summary
 */

import { readFileSync, existsSync } from 'node:fs';

const args = process.argv.slice(2);
const asJson = args.includes('--json');
const base = (args.find((a) => a.startsWith('http')) ?? 'http://localhost:3000').replace(/\/$/, '');

/** Crawl ceiling. The site is ~60 pages; this is a runaway guard, not a budget. */
const MAX_PAGES = 400;

/** SERP truncation points, from docs/SEO_LLM_STRATEGY.md §2. */
const TITLE_MIN = 50;
const TITLE_MAX = 60;
const DESC_MIN = 140;
const DESC_MAX = 155;

const problems = [];
const notes = [];
function fail(group, message) {
  problems.push({ group, message });
}
function note(group, message) {
  notes.push({ group, message });
}

// ── extraction ─────────────────────────────────────────────────────────────

const strip = (html) =>
  html
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();

function decode(text) {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&mdash;/g, '—')
    .replace(/&rsquo;/g, '’')
    .replace(/&ldquo;/g, '“')
    .replace(/&rdquo;/g, '”')
    .replace(/&nbsp;/g, ' ');
}

function extract(html, url) {
  const title = decode(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.trim() ?? '');

  const description = decode(
    html.match(/<meta[^>]+name="description"[^>]+content="([^"]*)"/i)?.[1] ??
      html.match(/<meta[^>]+content="([^"]*)"[^>]+name="description"/i)?.[1] ??
      '',
  );

  const canonical = html.match(/<link[^>]+rel="canonical"[^>]+href="([^"]*)"/i)?.[1] ?? null;
  const robots = html.match(/<meta[^>]+name="robots"[^>]+content="([^"]*)"/i)?.[1] ?? null;

  const h1s = [...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map((m) => strip(m[1]));

  /**
   * Internal links. `href` values only — the crawler never invents a URL, so a
   * page that cannot be reached by following links from the homepage or the
   * sitemap is genuinely unreachable, which is what check 5 is about.
   */
  const links = new Set();
  for (const m of html.matchAll(/<a[^>]+href="([^"#?]*)(?:[#?][^"]*)?"/gi)) {
    const href = m[1];
    if (!href || href.startsWith('mailto:') || href.startsWith('tel:')) continue;
    if (/^https?:\/\//i.test(href)) {
      if (href.startsWith(base)) links.add(new URL(href).pathname.replace(/\/$/, '') || '/');
      continue;
    }
    if (href.startsWith('/')) links.add(href.replace(/\/$/, '') || '/');
  }

  // JSON-LD, handed to a real parser.
  const schemas = [];
  for (const m of html.matchAll(
    /<script[^>]+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi,
  )) {
    try {
      const parsed = JSON.parse(m[1]);
      const nodes = parsed['@graph'] ?? (Array.isArray(parsed) ? parsed : [parsed]);
      for (const node of nodes) if (node && node['@type']) schemas.push(node);
    } catch (error) {
      fail('schema', `${url} — a JSON-LD block does not parse: ${error.message}`);
    }
  }

  const images = [...html.matchAll(/<img\b[^>]*>/gi)].map((m) => m[0]);
  const imagesWithoutAlt = images.filter((tag) => !/\balt=/.test(tag)).length;

  const tokens = (html.match(/\[\[NEEDS_VERIFICATION/g) ?? []).length;

  const og = {
    title: html.match(/<meta[^>]+property="og:title"[^>]+content="([^"]*)"/i)?.[1] ?? null,
    image: html.match(/<meta[^>]+property="og:image"[^>]+content="([^"]*)"/i)?.[1] ?? null,
    width: html.match(/<meta[^>]+property="og:image:width"[^>]+content="([^"]*)"/i)?.[1] ?? null,
    height: html.match(/<meta[^>]+property="og:image:height"[^>]+content="([^"]*)"/i)?.[1] ?? null,
    twitterCard: html.match(/<meta[^>]+name="twitter:card"[^>]+content="([^"]*)"/i)?.[1] ?? null,
  };

  return {
    title,
    description,
    canonical,
    robots,
    h1s,
    links: [...links],
    schemas,
    images: images.length,
    imagesWithoutAlt,
    tokens,
    og,
    bytes: html.length,
  };
}

// ── crawl ──────────────────────────────────────────────────────────────────

const pages = new Map(); // path -> record
const inbound = new Map(); // path -> Set of paths linking to it
const redirects = new Map(); // path -> location

function recordInbound(from, to) {
  if (!inbound.has(to)) inbound.set(to, new Set());
  inbound.get(to).add(from);
}

async function sitemapPaths() {
  const res = await fetch(`${base}/sitemap.xml`);
  if (!res.ok) {
    fail('sitemap', `/sitemap.xml returned ${res.status}`);
    return [];
  }
  const xml = await res.text();
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(
    (m) => new URL(m[1].trim()).pathname.replace(/\/$/, '') || '/',
  );
}

async function crawl(seeds) {
  const queue = [...seeds];
  const seen = new Set(queue);

  while (queue.length > 0 && pages.size < MAX_PAGES) {
    const path = queue.shift();
    let res;
    try {
      res = await fetch(`${base}${path}`, { redirect: 'manual' });
    } catch (error) {
      fail('crawl', `${path} — request failed: ${error.message}`);
      continue;
    }

    if (res.status >= 300 && res.status < 400) {
      redirects.set(path, res.headers.get('location'));
      pages.set(path, { status: res.status, redirect: res.headers.get('location') });
      continue;
    }

    const html = res.status === 200 ? await res.text() : '';
    const record = res.status === 200 ? extract(html, path) : {};
    pages.set(path, { status: res.status, ...record });

    for (const link of record.links ?? []) {
      recordInbound(path, link);
      if (!seen.has(link)) {
        seen.add(link);
        queue.push(link);
      }
    }
  }

  if (pages.size >= MAX_PAGES) fail('crawl', `crawl ceiling of ${MAX_PAGES} pages hit`);
}

// ── the ten checks ─────────────────────────────────────────────────────────

function checkStatuses() {
  for (const [path, page] of pages) {
    if (page.status === 200) continue;
    if (page.status >= 300 && page.status < 400) continue; // handled by the hop check
    const from = [...(inbound.get(path) ?? [])];
    fail(
      'links',
      `${path} returned ${page.status}${from.length ? ` — linked from ${from.slice(0, 3).join(', ')}` : ''}`,
    );
  }
}

function checkTitlesAndDescriptions() {
  const titles = new Map();
  const descriptions = new Map();

  for (const [path, page] of pages) {
    if (page.status !== 200) continue;
    const indexable = !/noindex/i.test(page.robots ?? '');

    if (!page.title) {
      fail('metadata', `${path} has no <title>`);
    } else if (indexable) {
      if (!titles.has(page.title)) titles.set(page.title, []);
      titles.get(page.title).push(path);
      const length = page.title.length;
      if (length > TITLE_MAX) {
        fail('metadata', `${path} title is ${length} chars, over ${TITLE_MAX} — it will truncate`);
      } else if (length < TITLE_MIN) {
        note('metadata', `${path} title is ${length} chars, under ${TITLE_MIN}`);
      }
    }

    if (!page.description) {
      if (indexable) fail('metadata', `${path} has no meta description`);
    } else if (indexable) {
      if (!descriptions.has(page.description)) descriptions.set(page.description, []);
      descriptions.get(page.description).push(path);
      const length = page.description.length;
      if (length > DESC_MAX) {
        fail('metadata', `${path} description is ${length} chars, over ${DESC_MAX}`);
      } else if (length < DESC_MIN) {
        note('metadata', `${path} description is ${length} chars, under ${DESC_MIN}`);
      }
    }
  }

  for (const [title, paths] of titles) {
    if (paths.length > 1) {
      fail('metadata', `duplicate title on ${paths.join(', ')} — "${title.slice(0, 60)}"`);
    }
  }
  // The description itself is not quoted in the message — 155 characters of
  // prose repeated for every duplicate makes the report unreadable, and the
  // paths are what somebody needs in order to go and fix it.
  for (const paths of descriptions.values()) {
    if (paths.length > 1) {
      fail('metadata', `duplicate description on ${paths.join(', ')}`);
    }
  }
}

function checkHeadings() {
  for (const [path, page] of pages) {
    if (page.status !== 200) continue;
    if (page.h1s.length === 0) fail('headings', `${path} has no <h1>`);
    else if (page.h1s.length > 1) {
      fail('headings', `${path} has ${page.h1s.length} <h1> elements: ${page.h1s.join(' | ')}`);
    }
  }
}

function checkCanonicals() {
  for (const [path, page] of pages) {
    if (page.status !== 200) continue;
    if (/noindex/i.test(page.robots ?? '')) continue;
    if (!page.canonical) {
      fail('canonical', `${path} has no canonical`);
      continue;
    }
    const canonicalPath = new URL(page.canonical).pathname.replace(/\/$/, '') || '/';
    if (canonicalPath !== path) {
      fail('canonical', `${path} canonical points at ${canonicalPath} — not self-referencing`);
    }
  }
}

function checkOrphans(sitemap) {
  for (const path of sitemap) {
    if (path === '/') continue; // the homepage needs no inbound link
    const from = inbound.get(path);
    if (!from || from.size === 0) {
      fail(
        'orphans',
        `${path} is in the sitemap but NO page links to it — a page with no inbound internal link does not exist`,
      );
    }
  }
}

function checkSitemapMatchesSite(sitemap) {
  const sitemapSet = new Set(sitemap);

  for (const path of sitemap) {
    const page = pages.get(path);
    if (!page) {
      fail('sitemap', `${path} is in the sitemap but was not reachable`);
    } else if (page.status !== 200) {
      fail('sitemap', `${path} is in the sitemap and returns ${page.status}`);
    } else if (/noindex/i.test(page.robots ?? '')) {
      fail('sitemap', `${path} is in the sitemap and is marked noindex — contradictory`);
    }
  }

  // The reverse: an indexable 200 reached by crawling that the sitemap omits.
  for (const [path, page] of pages) {
    if (page.status !== 200) continue;
    if (/noindex/i.test(page.robots ?? '')) continue;
    if (!sitemapSet.has(path)) {
      fail('sitemap', `${path} is indexable and reachable but ABSENT from the sitemap`);
    }
  }
}

function checkNoindex() {
  for (const [path, page] of pages) {
    if (page.status !== 200) continue;
    const isNoindex = /noindex/i.test(page.robots ?? '');
    const shouldBeNoindex = /^\/admin(\/|$)/.test(path) || /^\/orders\//.test(path);
    if (shouldBeNoindex && !isNoindex) {
      fail('noindex', `${path} MUST be noindex and is not`);
    }
    if (!shouldBeNoindex && isNoindex) {
      note('noindex', `${path} is noindex — confirm that is intended`);
    }
  }
}

function checkTokens() {
  for (const [path, page] of pages) {
    if (page.status !== 200 || !page.tokens) continue;
    fail(
      'tokens',
      `${path} carries ${page.tokens} [[NEEDS_VERIFICATION]] token(s) — brief PART 2.2 forbids launching with one on a public page`,
    );
  }
}

/**
 * SHARE IMAGES (added in the Sprint 13 restart, after V45 closed in 12p).
 *
 * CLAUDE.md §7 asks for a real share image on every page, and V45 was the
 * site-wide default being a 225x225 logo for two sprints without anything
 * failing. So: every indexable page names an og:image, the file loads as an
 * image, and the large Twitter card is only claimed for an image big enough
 * to carry it. The image URLs are absolute on the production domain, so they
 * are fetched from the server under test instead: the domain still serves the
 * old site until cutover. A size other than 1200x630 is a note, not a
 * failure: two article covers are cut at 40:21 from sources too small for it.
 */
async function checkShareImages() {
  const checked = new Map(); // url -> problem message, or null when fine
  for (const [path, page] of pages) {
    if (page.status !== 200 || /noindex/i.test(page.robots ?? '')) continue;
    const { image, width, height, twitterCard } = page.og ?? {};
    if (!image) {
      fail('share', `${path} has no og:image`);
      continue;
    }
    if (!checked.has(image)) {
      const local = `${base}${new URL(image, base).pathname}`;
      const res = await fetch(local).catch(() => null);
      const type = res?.headers.get('content-type') ?? '';
      checked.set(
        image,
        !res || res.status !== 200 || !type.startsWith('image/')
          ? `og:image ${image} returns ${res ? `${res.status} ${type}` : 'no response'}`
          : null,
      );
    }
    if (checked.get(image)) fail('share', `${path} — ${checked.get(image)}`);
    if (width !== '1200' || height !== '630') {
      note('share', `${path} share image is ${width ?? '?'}x${height ?? '?'}, not 1200x630`);
    }
    if (twitterCard === 'summary_large_image' && (Number(width) < 300 || Number(height) < 157)) {
      fail('share', `${path} claims a large Twitter card for a ${width}x${height} image`);
    }
  }
}

function checkImages() {
  for (const [path, page] of pages) {
    if (page.status !== 200 || !page.imagesWithoutAlt) continue;
    fail('images', `${path} has ${page.imagesWithoutAlt} <img> without an alt attribute`);
  }
}

function checkSchema() {
  /** Required types per route shape. Organization and WebSite are global. */
  const required = [
    [/^\/$/, ['Organization', 'WebSite']],
    [/^\/solutions\/[^/]+$/, ['BreadcrumbList', 'Service']],
    [/^\/products\/[^/]+$/, ['BreadcrumbList', 'Product']],
    [/^\/industries\/[^/]+$/, ['BreadcrumbList']],
    [/^\/resources\/blog\/[^/]+$/, ['BreadcrumbList', 'Article']],
    [/^\/about\/coverage$/, ['BreadcrumbList']],
    [/^\/resources\/faqs$/, ['BreadcrumbList', 'FAQPage']],
  ];

  for (const [path, page] of pages) {
    if (page.status !== 200) continue;
    const types = new Set(
      page.schemas.flatMap((s) => (Array.isArray(s['@type']) ? s['@type'] : [s['@type']])),
    );

    for (const [pattern, needed] of required) {
      if (!pattern.test(path)) continue;
      for (const type of needed) {
        if (!types.has(type)) fail('schema', `${path} is missing ${type} schema`);
      }
    }

    // Never markup that contradicts the visible page, and never a review
    // without genuine collected reviews (CLAUDE.md §7).
    if (types.has('Review') || types.has('AggregateRating')) {
      fail(
        'schema',
        `${path} emits ${types.has('Review') ? 'Review' : 'AggregateRating'} schema — forbidden without genuine collected reviews`,
      );
    }

    // An Offer must carry a real price.
    for (const node of page.schemas) {
      const offers = node.offers ? (Array.isArray(node.offers) ? node.offers : [node.offers]) : [];
      for (const offer of offers) {
        if (offer && offer.price === undefined && offer.lowPrice === undefined) {
          fail('schema', `${path} emits an Offer with no price`);
        }
      }
    }
  }
}

async function checkRedirectHops() {
  if (!existsSync('scripts/check-redirects.mjs')) return;
  const source = readFileSync('scripts/check-redirects.mjs', 'utf8');
  const block = source.match(/const EXPECTED = \[([\s\S]*?)\n\];/)?.[1] ?? '';
  const pairs = [...block.matchAll(/\[\s*'([^']+)'\s*,\s*'([^']+)'\s*\]/g)].map((m) => [
    m[1],
    m[2],
  ]);

  if (pairs.length === 0) {
    note('redirects', 'could not read the redirect map from check-redirects.mjs');
    return;
  }

  for (const [from, expected] of pairs) {
    const first = await fetch(`${base}${from}`, { redirect: 'manual' });
    if (first.status < 300 || first.status >= 400) {
      fail('redirects', `${from} returned ${first.status} instead of a redirect`);
      continue;
    }
    const location = (first.headers.get('location') ?? '').replace(base, '');
    const target = location.replace(/\/$/, '') || '/';

    if (target !== expected) {
      fail('redirects', `${from} redirects to ${target}, expected ${expected}`);
      continue;
    }

    /**
     * THE HOP CHECK, which is what Sprint 13 adds over Sprint 2.
     *
     * `check-redirects.mjs` deliberately does not require the destination to
     * return 200 — correct in Sprint 2, when several targets were unbuilt. At
     * an SEO gate a 301 into a 404 is a real defect: it spends the old URL's
     * authority on a dead end, and it is invisible unless something follows
     * the hop.
     */
    const second = await fetch(`${base}${target}`, { redirect: 'manual' });
    if (second.status >= 300 && second.status < 400) {
      const onward = (second.headers.get('location') ?? '').replace(base, '');
      fail('redirects', `CHAIN: ${from} -> ${target} -> ${onward} — must resolve in one hop`);
    } else if (second.status !== 200) {
      fail(
        'redirects',
        `${from} -> ${target} which returns ${second.status} — a 301 into a dead end`,
      );
    }
  }
}

async function checkLlmsTxt() {
  const res = await fetch(`${base}/llms.txt`);
  if (!res.ok) {
    fail('llms', `/llms.txt returned ${res.status}`);
    return;
  }
  const text = await res.text();

  // Every path it names must exist and be indexable.
  /**
   * ONLY paths on our own site.
   *
   * The first version took the pathname of every absolute URL it found, so
   * `https://wa.me/254759000111` — the WhatsApp link, which is correct and
   * belongs there — was reported as a broken route `/254759000111`. A tool that
   * invents a finding is worse than one that misses a real one, because the
   * next genuine finding gets read as noise too.
   */
  const site = new URL(base);
  const ours = (host) => host === site.host || host.endsWith('nebsamdigital.com');

  const listed = [...text.matchAll(/\bhttps?:\/\/[^\s)\]]+|(?<=\s)\/[a-z0-9/-]+/gi)]
    .map((m) => m[0])
    .flatMap((raw) => {
      if (!raw.startsWith('http')) return [raw];
      try {
        const parsed = new URL(raw);
        return ours(parsed.host) ? [parsed.pathname] : [];
      } catch {
        return [];
      }
    })
    .map((p) => p.replace(/[.,)]$/, '').replace(/\/$/, '') || '/')
    .filter((p) => p.startsWith('/'));

  for (const path of new Set(listed)) {
    const page = pages.get(path);
    if (!page) {
      const res2 = await fetch(`${base}${path}`, { redirect: 'manual' });
      if (res2.status !== 200) {
        fail('llms', `llms.txt names ${path}, which returns ${res2.status}`);
      }
      continue;
    }
    if (page.status !== 200) {
      fail('llms', `llms.txt names ${path}, which returns ${page.status}`);
    }
  }

  // It must carry the canonical description verbatim (CLAUDE.md §7).
  if (existsSync('lib/company.ts')) {
    const company = readFileSync('lib/company.ts', 'utf8');
    const canonical = company
      .match(/export const CANONICAL_DESCRIPTION =\s*([\s\S]*?);\n/)?.[1]
      ?.replace(/^\s*['"`]|['"`]\s*$/g, '')
      .replace(/['"`]\s*\+\s*\n\s*['"`]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
    if (canonical && canonical.length > 40) {
      const normalised = text.replace(/\s+/g, ' ');
      const opening = canonical.slice(0, 60);
      if (!normalised.includes(opening)) {
        fail('llms', 'llms.txt does not carry CANONICAL_DESCRIPTION verbatim');
      }
    }
  }
}

// ── run ────────────────────────────────────────────────────────────────────

const sitemap = await sitemapPaths();
await crawl(['/', ...sitemap]);

checkStatuses();
checkTitlesAndDescriptions();
checkHeadings();
checkCanonicals();
checkOrphans(sitemap);
checkSitemapMatchesSite(sitemap);
checkNoindex();
checkTokens();
checkImages();
checkSchema();
await checkShareImages();
await checkRedirectHops();
await checkLlmsTxt();

const crawled = [...pages.values()];
const ok = crawled.filter((p) => p.status === 200).length;

if (asJson) {
  console.log(
    JSON.stringify(
      { base, pages: pages.size, ok, problems, notes, sitemap: sitemap.length },
      null,
      2,
    ),
  );
} else {
  console.log(`\n  Crawl audit — ${base}`);
  console.log(
    `  ${pages.size} URLs reached · ${ok} returned 200 · ${sitemap.length} in the sitemap\n`,
  );

  const byGroup = new Map();
  for (const p of problems) {
    if (!byGroup.has(p.group)) byGroup.set(p.group, []);
    byGroup.get(p.group).push(p.message);
  }

  if (byGroup.size === 0) {
    console.log('  No problems found.\n');
  } else {
    for (const [group, messages] of byGroup) {
      console.log(`  ${group.toUpperCase()} — ${messages.length}`);
      for (const m of messages) console.log(`    - ${m}`);
      console.log('');
    }
  }

  if (notes.length > 0) {
    console.log(`  NOTES — ${notes.length} (not failures)`);
    for (const n of notes) console.log(`    · ${n.group}: ${n.message}`);
    console.log('');
  }

  if (problems.length === 0) {
    console.log('  crawl-audit: CLEAN against all ten criteria in SEO_LLM_STRATEGY §8\n');
  } else {
    console.log(`  crawl-audit: ${problems.length} problem(s). The gate is not met.\n`);
  }
}

process.exit(problems.length > 0 ? 1 : 0);
